#!/usr/bin/env node

var geojsonStream = require('geojson-stream')
var through = require('through2')
var polylabel = require('polylabel')
var turf = require('turf')

process.stdin.pipe(geojsonStream.parse())
.pipe(through.obj(write))
.pipe(geojsonStream.stringify())
.pipe(process.stdout)

function write (feat, _, next) {
  if (feat.geometry.coordinates.length) {
    var center
    if (feat.geometry.type === 'Polygon') {
      center = polylabel(feat.geometry.coordinates, 1.0)
    } else if (feat.geometry.type === 'MultiPolygon') {
      // it's still non-contiguous, use polylabel on the largest polygon
      var precision = feat.properties.id === '02' ? 500 : 1
      if (feat.geometry.type === 'MultiPolygon') {
        let sorted = feat.geometry.coordinates.sort((a, b) => {
          return turf.area(turf.polygon(a)) > turf.area(turf.polygon(b)) ? -1 : 1
        })
        center = polylabel(sorted[0], precision)
      } else {
        center = polylabel(feat.geometry.coordinates, precision)
      }
    }
    var dx = turf.distance(turf.point(center),
      turf.point([center[0] + center.distance, center[1]]))
    var dy = turf.distance(turf.point(center),
      turf.point([center[0], center[1] + center.distance]))
    this.push({
      type: 'Feature',
      id: feat.id,
      properties: { id: feat.properties.id, dx: dx, dy: dy },
      geometry: {
        'type': 'Point',
        'coordinates': [center[0], center[1]]
      }
    })
  }
  next()
}
