#!/usr/bin/env bash

TILESET=$1
FILENAME=$2
BUCKET="wapo-election-private-config"
KEY="backup/tiles/$TILESET.mbtiles"

if aws s3api head-object --bucket $BUCKET --key $KEY; then
  echo $KEY already exists in S3 bucket $BUCKET. Aborting.
  exit 1
fi

node_modules/.bin/mapbox-upload $TILESET $FILENAME
aws s3 cp $FILENAME "s3://$BUCKET/$KEY"
